const adminApi = (url, options) => fetch(`api/${url}`, options).then(async response => { const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.message || 'No fue posible completar la operación.'); return result; });
const money = value => `$${Number(value).toLocaleString('es-CO')}`;
let products = [];
function requireAdmin() { return adminApi('auth.php').then(result => { if (!result.user || result.user.rol !== 'administrador') window.location.href = 'login.html'; return result.user; }); }
function loadAdminData() {
  return Promise.all([adminApi('products.php'), adminApi('orders.php'), adminApi('promotions.php'), fetch('api/metrics.php').then(response => response.json())]).then(([productResult, orderResult, promotionResult, metricsResult]) => {
    products = productResult.products;
    const lowStock = products.filter(product => Number(product.cantidad_disponible) <= Number(product.stock_minimo));
    const metrics = metricsResult.metrics || {};
    document.querySelector('#stats').innerHTML = `<div><b>${Number(metrics.usuarios || 0)}</b><span>Usuarios</span></div><div><b>${products.length}</b><span>Productos</span></div><div><b>${orderResult.orders.length}</b><span>Pedidos</span></div><div class="warning-stat"><b>${lowStock.length}</b><span>Inventario bajo</span></div>`;
    document.querySelector('#products').innerHTML = products.map(product => `<div class="admin-product"><span><b>${product.nombre}</b><small>${product.cantidad_disponible} disponibles · ${product.estado}${Number(product.cantidad_disponible) <= Number(product.stock_minimo) ? ' · STOCK BAJO' : ''}</small></span><button data-edit="${product.id}">Editar</button><button data-delete="${product.id}">Eliminar</button></div>`).join('');
    document.querySelector('#orders').innerHTML = orderResult.orders.length ? orderResult.orders.slice(0, 10).map(order => `<div class="order-row"><span><b>#${order.id}</b> ${order.nombre || ''}<small>${order.correo || ''}</small></span><strong>${money(order.total)}</strong><select data-order="${order.id}"><option ${order.estado === 'recibido' ? 'selected' : ''}>recibido</option><option ${order.estado === 'en_revision' ? 'selected' : ''}>en_revision</option><option ${order.estado === 'confirmado' ? 'selected' : ''}>confirmado</option><option ${order.estado === 'cancelado' ? 'selected' : ''}>cancelado</option></select></div>`).join('') : '<p>No hay pedidos registrados.</p>';
    document.querySelector('#promotion-audience').textContent = `${promotionResult.audience} clientes con WhatsApp`;
    document.querySelector('#promotions').innerHTML = promotionResult.promotions.length ? promotionResult.promotions.map(promotion => `<div class="promotion-row"><span><b>${promotion.titulo}</b><small>${promotion.mensaje}</small></span><button data-toggle-promotion="${promotion.id}" data-active="${promotion.activa}">${Number(promotion.activa) ? 'Desactivar' : 'Activar'}</button><button data-send-promotion="${promotion.id}" ${Number(promotion.activa) ? '' : 'disabled'}>Enviar</button><button data-delete-promotion="${promotion.id}">Eliminar</button></div>`).join('') : '<p>No hay promociones guardadas.</p>';
  });
}
document.querySelector('#product-form').addEventListener('submit', event => {
  event.preventDefault(); const id = document.querySelector('#product-id').value;
  const payload = { id: id || undefined, nombre: document.querySelector('#product-name').value, descripcion: document.querySelector('#product-description').value, categoria_id: document.querySelector('#product-category').value, precio: document.querySelector('#product-price').value, cantidad_disponible: document.querySelector('#product-stock').value, stock_minimo: document.querySelector('#product-minimum').value };
  adminApi('products.php', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }).then(() => { event.target.reset(); document.querySelector('#product-id').value = ''; loadAdminData(); }).catch(error => { document.querySelector('#product-status').textContent = error.message; });
});
document.querySelector('#products').addEventListener('click', event => { const id = Number(event.target.dataset.edit || event.target.dataset.delete); if (!id) return; if (event.target.dataset.delete) { adminApi('products.php', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }).then(loadAdminData).catch(error => { document.querySelector('#product-status').textContent = error.message; }); return; } const product = products.find(item => Number(item.id) === id); document.querySelector('#product-id').value = product.id; document.querySelector('#product-name').value = product.nombre; document.querySelector('#product-description').value = product.descripcion; document.querySelector('#product-category').value = product.categoria_id; document.querySelector('#product-price').value = product.precio; document.querySelector('#product-stock').value = product.cantidad_disponible; document.querySelector('#product-minimum').value = product.stock_minimo; });
document.querySelector('#orders').addEventListener('change', event => { if (!event.target.dataset.order) return; adminApi('orders.php', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: event.target.dataset.order, estado: event.target.value }) }).then(loadAdminData).catch(error => { document.querySelector('#order-status').textContent = error.message; }); });
document.querySelector('#promotion-form').addEventListener('submit', event => { event.preventDefault(); adminApi('promotions.php', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ titulo: document.querySelector('#promotion-title').value, mensaje: document.querySelector('#promotion-message').value }) }).then(() => { event.target.reset(); document.querySelector('#promotion-status').textContent = 'Promoción guardada.'; return loadAdminData(); }).catch(error => { document.querySelector('#promotion-status').textContent = error.message; }); });
document.querySelector('#promotions').addEventListener('click', event => { const id = Number(event.target.dataset.togglePromotion || event.target.dataset.sendPromotion || event.target.dataset.deletePromotion); if (!id) return; const options = { method: event.target.dataset.togglePromotion ? 'PATCH' : event.target.dataset.deletePromotion ? 'DELETE' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(event.target.dataset.togglePromotion ? { id, activa: event.target.dataset.active !== '1' } : event.target.dataset.deletePromotion ? { id } : { action: 'send', id }) }; if (event.target.dataset.sendPromotion && !window.confirm('¿Enviar esta promoción a todos los clientes con WhatsApp?')) return; adminApi('promotions.php', options).then(result => { document.querySelector('#promotion-status').textContent = event.target.dataset.sendPromotion ? `Envío terminado: ${result.sent} enviados, ${result.failed} rechazados.` : 'Promoción actualizada.'; return loadAdminData(); }).catch(error => { document.querySelector('#promotion-status').textContent = error.message; }); });
document.querySelector('#logout').addEventListener('click', () => adminApi('auth.php', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'logout' }) }).then(() => { window.location.href = 'index.html'; }));
requireAdmin().then(loadAdminData).catch(() => { window.location.href = 'login.html'; });
